(part "PDB181-K415F-503B"
    (packageRef "PDB181K415F503B")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "652-PDB181K415F503B")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/PDB181-K415F-503B?qs=fgHA1UgJI8CfxbrAh7xxKw%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "PDB181-K415F-503B")
    (property "Description" "Potentiometers PANEL CONTROL 17MM-ST-CARBON")
    (property "Datasheet_Link" "https://componentsearchengine.com//PDB181-K415F-503B.pdf")
    (property "symbolName1" "PDB181-K415F-503B")
)
